### ISSUE TITLE
Highlights method not found

### ISSUE THREAD

**Issue by nvanexan** [stve/instapaper#6]
Trying to get highlights for a given bookmark_id in a Ruby on Rails application, I get the following error:

```NoMethodError: undefined method `highlights' for #<Instapaper::Client:0x007fe8125f1430>```

Here's the code that's calling the method:

```
authorization = Authorization.where("user_id = ? AND provider = ?", self.id, 'instapaper')[0]

credentials = {
    consumer_key: ENV['INSTAPAPER_CONSUMER_KEY'],
    consumer_secret: ENV['INSTAPAPER_CONSUMER_SECRET'],
    oauth_token: authorization.oauth_token,
    oauth_token_secret: authorization.oauth_secret,
  }

client = Instapaper::Client.new(credentials)
highlights = client.highlights(549634562)

```

Everything else is working well (i.e. I can get a list of folders, bookmarks, etc.).  Not sure why it's not recognizing the highlights method.  

I'm using gem 'instapaper', '~> 0.3.0'

**Comment by stve** [comment]
Hi @nvanexan 

The README reflects the unreleased version `1.x` which is a significant rewrite and adds support for highlights and updates to the latest version of the Instapaper API. Unfortunately, I've had issues with several endpoints and as a result, the version remains unreleased. I've reported these issues to Instapaper and am hoping to receive word back from them so that I can finally release 1.0. 

As chance would have it, the highlights API is one of the endpoints I've had difficulty working with. It seems to 500 right now.

I'll keep you posted

**Comment by stve** [comment]
I should have mentioned this, refer to this list for changes between `0.x` and `1.x` versions: https://github.com/stve/instapaper#changes-in-100

**Comment by nvanexan** [comment]
Okay.  Thanks, Steve.  That's very helpful.  I'll stay tuned for 1.x !!  :)

**Comment by stve** [comment]
@nvanexan I was able to figure out how to get highlights working, give `1.0.0.pre2` a shot.

**Comment by stve** [comment]
@nvanexan i'm going to close this since I didn't hear back from you. I'm planning on releasing 1.0 very soon so it'd be great to get your thoughts on the pre-release version in advance of that if you are able to find some time to test it out. Thanks!
